### ISSUE TITLE
Meta issue: action items from 11/2/23

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/presentation-exchange#457]
We attempted to summarize IIW PE-related takeaways. Public sources:
- https://self-issued.info/presentations/What_does_PE_do_and_what_do_we_need-Part_3.pptx
- https://self-issued.info/presentations/What_does_PE_do_and_what_do_we_need-Part_3_Notes.txt

We wrote up remaining issues and have the following takeaways
- [ ] Follow up on documented 2.1 issues
    - [ ] Ask for clarification
    - [ ] Ask if 2.1 list is a complete set; ie anything missing?
- [ ] Anything else missing?

**Comment by dif-admin** [comment]
Finished
